### ISSUE TITLE
Error while running app.js

### ISSUE THREAD

**Issue by akshayvr-programmer** [yashrajpahwa/easyauth#1]
Hi Yashraj,
I checked out the authentication API. It's pretty cool! Although, I was getting an error while running app.js. I thought this might interest you.

Here's the error:
- /workspace/easyauth/app.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/workspace/easyauth/app.js:1:17)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/workspace/easyauth/app.js' ]
}

**Comment by yashrajpahwa** [comment]
Hi Akshay,

Glad you asked
- First of all, I am currently working on the API along with its documentation
- If you need to run the API you will have to have yarn installed after which you can run the ```yarn``` command then run ```yarn start```
- Please note that in the ```config/.env``` file you will have to put a MongoDB connection string too

Currently, the API has only one sample route that can either be used to ```GET``` data or ```POST``` data via its respective methods

Thanks,

Regards
Yashraj Pahwa

(if you have any more questions you may reopen this issue I am closing it for now)
